
--USERS-----
DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON
(PERSON_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
NAME VARCHAR(255) NOT NULL,
SPECIALITY VARCHAR(255) NOT NULL,
ROLE VARCHAR(255) NOT NULL,
YOB VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
RECORDS VARCHAR(255) DEFAULT NULL,
PRESCRIPTIONS VARCHAR(255) DEFAULT NULL);

---AUTORIZATION----
DROP TABLE IF EXISTS AUTHORIZATIONS;
CREATE TABLE AUTHORIZATIONS
(AUTH_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
REQUESTER_ID INT NOT NULL,
FOREIGN KEY(REQUESTER_ID) REFERENCES PERSON(PERSON_ID),
APPROVER_ID INT NOT NULL,
FOREIGN KEY(APPROVER_ID) REFERENCES PERSON(PERSON_ID),
REQUEST_TYPE VARCHAR(255) NOT NULL);